# Generated by Django 5.1.4 on 2025-01-09 02:07

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primario', colorfield.fields.ColorField(default='#8E44AD', help_text='Color principal de la tienda', image_field=None, max_length=25, samples=None, verbose_name='Color Primario')),
                ('color_secundario', colorfield.fields.ColorField(default='#E67E22', help_text='Color secundario de la tienda', image_field=None, max_length=25, samples=None, verbose_name='Color Secundario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tema', to='api.infonegocio')),
            ],
            options={
                'verbose_name': 'Tema de Tienda',
                'verbose_name_plural': 'Temas de Tiendas',
            },
        ),
    ]
