# Generated by Django 5.1.4 on 2025-01-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subcategoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='infonegocio',
            name='img_portada',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/img_portada/'),
        ),
    ]
