# Generated by Django 5.1.4 on 2025-01-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_infonegocio_img_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='infonegocio',
            name='moneda_principal',
            field=models.CharField(choices=[('CUP', 'CUP'), ('USD', 'USD'), ('EUR', 'EUR'), ('ZELLE', 'ZELLE'), ('MLC', 'MLC')], default='CUP', max_length=5),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ejemplo: 21.123456 o 21,123456', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ejemplo: -82.123456 o -82,123456', max_digits=9, null=True),
        ),
    ]
