# Generated by Django 5.1.4 on 2025-01-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_infonegocio_moneda_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infonegocio',
            name='moneda_principal',
        ),
    ]
