# Generated by Django 5.1.4 on 2025-01-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_infonegocio_moneda_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='infonegocio',
            name='moneda_principal',
            field=models.CharField(choices=[('CUP', 'CUP'), ('USD', 'USD'), ('EUR', 'EUR'), ('ZELLE', 'ZELLE'), ('MLC', 'MLC')], default='CUP', max_length=5),
        ),
    ]
