# Generated by Django 5.1.4 on 2025-01-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_infonegocio_moneda_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='infonegocio',
            name='acepta_transferencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infonegocio',
            name='hace_domicilio',
            field=models.BooleanField(default=False),
        ),
    ]
