# Generated by Django 5.1.4 on 2025-01-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_infonegocio_municipio_infonegocio_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infonegocio',
            name='favicon',
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='provincia',
            field=models.CharField(choices=[('Pinar del Río', 'Pinar del Río'), ('Artemisa', 'Artemisa'), ('La Habana', 'La Habana'), ('Mayabeque', 'Mayabeque'), ('Matanzas', 'Matanzas'), ('Cienfuegos', 'Cienfuegos'), ('Villa Clara', 'Villa Clara'), ('Sancti Spíritus', 'Sancti Spíritus'), ('Ciego de Ávila', 'Ciego de Ávila'), ('Camagüey', 'Camagüey'), ('Las Tunas', 'Las Tunas'), ('Holguín', 'Holguín'), ('Granma', 'Granma'), ('Santiago de Cuba', 'Santiago de Cuba'), ('Guantánamo', 'Guantánamo'), ('Isla de la Juventud', 'Isla de la Juventud')], default='Sancti Spíritus', max_length=50, verbose_name='Provincia'),
        ),
    ]
