# Generated by Django 5.1.4 on 2025-01-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_infonegocio_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infonegocio',
            name='descripcion',
            field=models.TextField(blank=True, default='Este negocio aún no tiene descripción', null=True),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='direccion',
            field=models.CharField(blank=True, default='Este negocio aún no ha configurado su dirección', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='horario',
            field=models.TextField(blank=True, default='Este negocio aún no ha configurado su horario', help_text='Horario de atención', null=True),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='img_portada',
            field=models.ImageField(blank=True, default='default/default_portada.jpg', null=True, upload_to='negocios/img_portada/'),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='logo',
            field=models.ImageField(blank=True, default='default/default_logo.jpg', null=True, upload_to='negocios/logos/'),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='moneda_principal',
            field=models.CharField(blank=True, choices=[('CUP', 'CUP'), ('USD', 'USD'), ('EUR', 'EUR'), ('ZELLE', 'ZELLE'), ('MLC', 'MLC')], default='CUP', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='municipio',
            field=models.CharField(blank=True, default='Jatibonico', max_length=50, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='provincia',
            field=models.CharField(blank=True, choices=[('Pinar del Río', 'Pinar del Río'), ('Artemisa', 'Artemisa'), ('La Habana', 'La Habana'), ('Mayabeque', 'Mayabeque'), ('Matanzas', 'Matanzas'), ('Cienfuegos', 'Cienfuegos'), ('Villa Clara', 'Villa Clara'), ('Sancti Spíritus', 'Sancti Spíritus'), ('Ciego de Ávila', 'Ciego de Ávila'), ('Camagüey', 'Camagüey'), ('Las Tunas', 'Las Tunas'), ('Holguín', 'Holguín'), ('Granma', 'Granma'), ('Santiago de Cuba', 'Santiago de Cuba'), ('Guantánamo', 'Guantánamo'), ('Isla de la Juventud', 'Isla de la Juventud')], default='Sancti Spíritus', max_length=50, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='infonegocio',
            name='telefono',
            field=models.CharField(blank=True, default='Sin teléfono', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='default/default_producto.jfif', null=True, upload_to='productos/'),
        ),
    ]
