# Generated by Django 5.1.4 on 2025-01-17 15:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_negociouser_negocio_alter_negociouser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='default/default_producto.jfif', null=True, upload_to=api.models.Producto.producto_imagen_path),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
