# Generated by Django 4.2 on 2025-02-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_licencia_tipo_licencia_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='primera_licencia_pagada',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ya pagó su primera licencia'),
        ),
    ]
